services:
  db:
    image: mysql:8.0.33
    container_name: db
    restart: always
    user: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    expose:
      - 3306

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    tty: true
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8000:80

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: 
  wordpress: 
